name: IFTTT-CallBack-Work

on: 
  repository_dispatch:
    types: seo

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: Hello
      run: |
        echo Hello World!
        echo ${{ github.event.client_payload.url }}
        
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
